
const ACTIONS = {
  INCREASE_FONT: "INCREASE_FONT",
  DECREASE_FONT: "DECREASE_FONT",
  TAKE_SNAPSHOT: "TAKE_SNAPSHOT",
  CLEAR_SELECTIONS: "CLEAR_SELECTIONS",
  CHANGE_COLOR: "CHANGE_COLOR"
}
export {ACTIONS}