
const ACTIONS = {
  SCROLL_END: "SCROLL_END",
  TAKE_SNAPSHOT: "TAKE_SNAPSHOT",
  CLEAR_SELECTIONS: "CLEAR_SELECTIONS",
  CHANGE_COLOR: "CHANGE_COLOR",
  SELECT_ALL: "SELECT_ALL",
  DELETE_SELECTED_ITEMS: "DELETE_SELECTED_ITEMS"
}
export {ACTIONS}